language: go
go:
  - "1.10.x"

matrix:
  include:
    - os: linux
      env:
        - SUDO=""
          USER_FLAG="--user"
    - os: osx
      env:
        - SUDO="sudo"
          USER_FLAG=""

before_script:
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"  # https://github.com/travis-ci/travis-ci/issues/8920#issuecomment-352661024
# Run gofmt and lint serially to avoid confusing output. Run tests in parallel
# for speed.
  - ${SUDO} python -m pip install pytest pytest-cov coverage ${USER_FLAG} 

script:
  # Install the thing
  - cd grumpy-tools-src
  - ${SUDO} python -m pip install . ${USER_FLAG}
  - which grumpy
  - cd ../grumpy-runtime-src
  - ${SUDO} python -m pip install . ${USER_FLAG}
  # Test the thing
  - cd ../grumpy-tools-src
  - pytest
  - cd ../grumpy-runtime-src
  - make gofmt lint && make -j2 test

# OSX swallows error logs: https://github.com/travis-ci/travis-ci/issues/6018
after_error:
  - echo "== End of test log ==""
